name:                poly-assumptions
version:             0.1.0.0
github:              "githubuser/poly-assumptions"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/poly-assumptions#readme>

dependencies:
- base >= 4.7 && < 5
- array # need for happy
- containers
- unordered-containers
- hashable
- dlist
- text
- mtl
- transformers
- enummapset
- microlens
- microlens-th
- prettyprinter
- haskeline

default-extensions:
- FlexibleInstances
- FlexibleContexts
- InstanceSigs
- MultiParamTypeClasses
- GeneralizedNewtypeDeriving
- OverloadedStrings
- ConstraintKinds
- LambdaCase
- EmptyCase
- BangPatterns
- TypeApplications
- StandaloneDeriving
- DeriveGeneric
- ScopedTypeVariables
- RankNTypes
- TemplateHaskell
- PatternSynonyms
- PartialTypeSignatures

ghc-options:
  - -Wall
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

build-tools:
  - alex
  - happy

library:
  source-dirs: src

executables:
  poly-assumptions-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - poly-assumptions

tests:
  poly-assumptions-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - poly-assumptions
    - hspec
